# Opening HDF5 File

In [2]:
using HDF5
fname = "SeaFreeze_table.hdf5"
# Displaying all of the file's information
fid = h5open(fname, "r")

🗂️ HDF5.File: (read-only) SeaFreeze_table.hdf5
├─ 📂 Entropy
│  ├─ 🔢 Data
│  ├─ 🔢 Dimensions
│  ├─ 🔢 Elements
│  ├─ 🔢 Shape
│  ├─ 🔢 TypeofElements
│  └─ 🔢 TypeofObject
├─ 📂 Pressure
│  ├─ 🔢 Data
│  ├─ 🔢 Dimensions
│  ├─ 🔢 Elements
│  ├─ 🔢 Shape
│  ├─ 🔢 TypeofElements
│  └─ 🔢 TypeofObject
└─ 📂 Temperature
   ├─ 🔢 Data
   ├─ 🔢 Dimensions
   ├─ 🔢 Elements
   ├─ 🔢 Shape
   ├─ 🔢 TypeofElements
   └─ 🔢 TypeofObject

In [3]:
# Reading Data from file
entropy = fid["Entropy"];
pressure = fid["Pressure"];
temperature = fid["Temperature"];

In [4]:
# Displaying the contents in Entropy group 
for obj in entropy
  data = read(obj)
  display(data)
end

# Accessing Entropy contents that I want
ed = read(entropy, "Data");

10×225 Matrix{Float64}:
 -2830.02  -2821.11  -2812.2   …  336.957  351.061  365.116  379.123
 -2830.16  -2821.26  -2812.36     334.534  348.541  362.501  376.415
 -2830.31  -2821.41  -2812.51     331.999  345.917  359.789  373.617
 -2830.45  -2821.56  -2812.67     329.358  343.193  356.984  370.731
 -2830.59  -2821.7   -2812.82     326.617  340.375  354.09   367.763
 -2830.72  -2821.84  -2812.96  …  323.781  337.468  351.113  364.716
 -2830.86  -2821.98  -2813.11     320.855  334.477  348.057  361.595
 -2830.99  -2822.12  -2813.25     317.846  331.406  344.926  358.404
 -2831.12  -2822.25  -2813.39     314.758  328.262  341.725  355.148
 -2831.25  -2822.39  -2813.53     311.596  325.048  338.459  351.83

"No. of dimensions: 2"

"Total number of elements: 2250"

"Shape of array(row,col): (225, 10)"

"Array stores elements of type: float64"

"Array is of type: <class 'numpy.ndarray'>"

In [5]:
# Displaying the data in Pressure group 
for obj in pressure
  data = read(obj)
  display(data)
end

# Accessing Pressure content that I want
pd = read(pressure, "Data");

10-element Vector{Float64}:
  0.0
 10.0
 20.0
 30.0
 40.0
 50.0
 60.0
 70.0
 80.0
 90.0

"No. of dimensions: 1"

"Total number of elements: 10"

"Shape of array(row,col): (10,)"

"Array stores elements of type: float64"

"Array is of type: <class 'numpy.ndarray'>"

In [6]:
# Displaying the data in Temperature group 
for obj in temperature
  data = read(obj)
  display(data)
end

# Accessing Temperature content that I want
td = read(temperature, "Data");

225-element Vector{Float64}:
  75.0
  76.0
  77.0
  78.0
  79.0
  80.0
  81.0
  82.0
  83.0
  84.0
  85.0
  86.0
  87.0
   ⋮
 288.0
 289.0
 290.0
 291.0
 292.0
 293.0
 294.0
 295.0
 296.0
 297.0
 298.0
 299.0

"No. of dimensions: 1"

"Total number of elements: 225"

"Shape of array(row,col): (225,)"

"Array stores elements of type: float64"

"Array is of type: <class 'numpy.ndarray'>"

# Closing HDF5 File

In [7]:
# Close file
close(fid)

In [8]:
display(ed)

10×225 Matrix{Float64}:
 -2830.02  -2821.11  -2812.2   …  336.957  351.061  365.116  379.123
 -2830.16  -2821.26  -2812.36     334.534  348.541  362.501  376.415
 -2830.31  -2821.41  -2812.51     331.999  345.917  359.789  373.617
 -2830.45  -2821.56  -2812.67     329.358  343.193  356.984  370.731
 -2830.59  -2821.7   -2812.82     326.617  340.375  354.09   367.763
 -2830.72  -2821.84  -2812.96  …  323.781  337.468  351.113  364.716
 -2830.86  -2821.98  -2813.11     320.855  334.477  348.057  361.595
 -2830.99  -2822.12  -2813.25     317.846  331.406  344.926  358.404
 -2831.12  -2822.25  -2813.39     314.758  328.262  341.725  355.148
 -2831.25  -2822.39  -2813.53     311.596  325.048  338.459  351.83

In [9]:
display(pd)

10-element Vector{Float64}:
  0.0
 10.0
 20.0
 30.0
 40.0
 50.0
 60.0
 70.0
 80.0
 90.0

In [10]:
display(td)

225-element Vector{Float64}:
  75.0
  76.0
  77.0
  78.0
  79.0
  80.0
  81.0
  82.0
  83.0
  84.0
  85.0
  86.0
  87.0
   ⋮
 288.0
 289.0
 290.0
 291.0
 292.0
 293.0
 294.0
 295.0
 296.0
 297.0
 298.0
 299.0

In [11]:
using Interpolations

In [43]:
f(temperature,pressure) = log(temperature+pressure)
entropy = ed;
pressure = pd*1e+6;
temperature = td;
xs = temperature
ys = pressure
entropy = [f(temperature,pressure) for temperature in xs, pressure in ys]

# linear interpolation
interp_linear = linear_interpolation((xs, ys), entropy)
interp_linear(100, 1)

4.6051713372816385

10-element Vector{Float64}:
 0.0
 1.0e7
 2.0e7
 3.0e7
 4.0e7
 5.0e7
 6.0e7
 7.0e7
 8.0e7
 9.0e7

In [42]:
temperature

225-element Vector{Float64}:
  75.0
  76.0
  77.0
  78.0
  79.0
  80.0
  81.0
  82.0
  83.0
  84.0
  85.0
  86.0
  87.0
   ⋮
 288.0
 289.0
 290.0
 291.0
 292.0
 293.0
 294.0
 295.0
 296.0
 297.0
 298.0
 299.0